### ISSUE TITLE
Can't find extension in Obsidian plugin list

### ISSUE THREAD

**Issue by anutator** [ozntel/obsidian-link-converter#26]
Obsidian 1.2.8. Didn't find an extension. I had to copy files from your release page manually to plugin's folder.

**Comment by ozntel** [comment]
Are you sure you searched correctly? Here you can see the results from Community Plugins:

![image](https://github.com/ozntel/obsidian-link-converter/assets/55187568/d9942b75-6dea-4e35-bafa-eaa0146b3403)

**Comment by anutator** [comment]
Thank you.
