### ISSUE TITLE
great plugin, I have a concern about wiki to markdown

### ISSUE THREAD

**Issue by BuaaLzd** [ozntel/obsidian-link-converter#4]
Hi, Ozan, Thanks for your work. this plugin is very nice to deal with link issues. I use obsidian and logseq simultaneously, and logseq can't read the wikilinks, could you provide another convertion option, which can convert wiki to markdown link. I know there is a plugin "wkilinks to mdlinks" in the community, but it can't do the batch converting job like yours, the only plugin can do batch converting for a file or the whole vault. Thanks.

**Comment by ozntel** [comment]
The plugin already converts Wikilinks to Markdown Link. What exactly doesn't work for you? Please provide an example

**Comment by ozntel** [comment]
I am closing this now. In case you have any issue, feel free to write here
