### ISSUE TITLE
can `All Links to Relative Path` keep filename extension

### ISSUE THREAD

**Issue by lzyerste** [ozntel/obsidian-link-converter#7]
hi, ozan, this plugin is really great, especially when I move documents around.

I use `All Links to Relative Path` to adjust links to correct relative path, but it would chop filename extension. For example, `.md` is removed.

Is there a way to keep the filename extension? Obsidian could keep extension when insert links when use relative path.

Thanks

**Comment by ozntel** [comment]
Hi @lzyerste, I'm glad the plugin is helpful. 
I actually tried with Obsidian's default relative path, however, it looks like Obsidian by default generates a link without `.md` extension. Can you explain which preferences are ending up with such a link as you mentioned?

**Comment by lzyerste** [comment]
hi @ozntel 

My settings about `Files & Links` are:

- New link format: Relative path to file
- Use [[Wikilinks]]: OFF

Suppose there's a file `test.md`. Type `[[test`, in the popup, pick `test`, it would become `[test](test.md)`.

**Comment by ozntel** [comment]
New release should solve the issue. If the final format is markdown, the plugin will automatically include the extension. Let me know if the issue still persists.
